parameters:
- name: AdditionalParameters
  type: object
- name: CloudConfig
  type: object
  default: {}
- name: MatrixConfigs
  type: object
  default: []
- name: MatrixFilters
  type: object
  default: []
- name: JobTemplatePath
  type: string
# Set this to false to do a full checkout for private repositories with the azure pipelines service connection
- name: SparseCheckout
  type: boolean
  default: true

jobs:
- job: generate_matrix
  variables:
    displayNameFilter: $[ coalesce(variables.jobMatrixFilter, '.*') ]
  pool:
    name: azsdk-pool-mms-ubuntu-1804-general
    vmImage: MMSUbuntu18.04
  displayName: Generate Job Matrix
  steps:
    - ${{ if parameters.SparseCheckout }}:
      - checkout: none

      - pwsh: |
          git clone --no-checkout --filter=tree:0 git://github.com/$(Build.Repository.Name).git .
          git sparse-checkout init
          if ("${{ parameters.AdditionalParameters.ServiceDirectory }}") {
            git sparse-checkout set eng sdk/${{ parameters.AdditionalParameters.ServiceDirectory}}
          } else {
            git sparse-checkout set eng
          }
          git checkout $(Build.SourceVersion)
        workingDirectory: $(Build.Repository.LocalPath)

    - ${{ each config in parameters.MatrixConfigs }}:
      - ${{ if eq(config.GenerateVMJobs, 'true') }}:
        - task: Powershell@2
          inputs:
            pwsh: true
            ${{ if parameters.SparseCheckout }}:
              workingDirectory: $(Build.Repository.LocalPath)
            filePath: eng/common/scripts/job-matrix/Create-JobMatrix.ps1
            arguments: >
              -ConfigPath ${{ config.Path }}
              -Selection ${{ config.Selection }}
              -DisplayNameFilter "$(displayNameFilter)"
              -Filters "${{ join('","', parameters.MatrixFilters) }}","container=^$","SupportedClouds=^$|${{ parameters.CloudConfig.Cloud }}"
              -NonSparseParameters "${{ join('","', config.NonSparseParameters) }}"
          displayName: Generate VM Job Matrix ${{ config.Name }}
          name: generate_vm_job_matrix_${{ config.Name }}

      - ${{ if eq(config.GenerateContainerJobs, 'true') }}:
        - task: Powershell@2
          inputs:
            pwsh: true
            ${{ if parameters.SparseCheckout }}:
              workingDirectory: $(Build.Repository.LocalPath)
            filePath: eng/common/scripts/job-matrix/Create-JobMatrix.ps1
            arguments: >
              -ConfigPath ${{ config.Path }}
              -Selection ${{ config.Selection }}
              -DisplayNameFilter "$(displayNameFilter)"
              -Filters "${{ join('","', parameters.MatrixFilters) }}", "container=.*", "SupportedClouds=^$|${{ parameters.CloudConfig.Cloud }}"
              -NonSparseParameters "${{ join('","', config.NonSparseParameters) }}"
          displayName: Generate Container Job Matrix
          name: generate_container_job_matrix_${{ config.Name }}

- ${{ each config in parameters.MatrixConfigs }}:
  - ${{ if eq(config.GenerateVMJobs, 'true') }}:
    - template: ${{ parameters.JobTemplatePath }}
      parameters:
        UsePlatformContainer: false
        Matrix: dependencies.generate_matrix.outputs['generate_vm_job_matrix_${{ config.Name }}.matrix']
        DependsOn: generate_matrix
        CloudConfig: ${{ parameters.CloudConfig }}
        ${{ each param in parameters.AdditionalParameters }}:
          ${{ param.key }}: ${{ param.value }}

  - ${{ if eq(config.GenerateContainerJobs, 'true') }}:
    - template: ${{ parameters.JobTemplatePath }}
      parameters:
        UsePlatformContainer: true
        Matrix: dependencies.generate_matrix.outputs['generate_container_job_matrix_${{ config.Name }}.matrix']
        DependsOn: generate_matrix
        CloudConfig: ${{ parameters.CloudConfig }}
        ${{ each param in parameters.AdditionalParameters }}:
          ${{ param.key }}: ${{ param.value }}
